"""
Long-term memory helpers.

Long-term memory here is a hybrid of:
  1. Structured preferences (budget, preferred make/body type, liked listing
     ids) - cheap to store/query, and directly usable for filtering/lead
     scoring.
  2. A rolling natural-language summary of past sessions ("returning-user
     digest"), generated by the LLM itself. This is the more "cookie points"
     part: instead of replaying the entire chat history of every past
     session (expensive, noisy), we compress each finished session down to
     1-3 sentences and append/merge that into `long_term_summary`. On a new
     session, both pieces are injected into the system prompt so the agent
     can say things like "Welcome back Sarah - last time you were eyeing a
     white SUV under 100k, did that Velar work out?"
"""
from __future__ import annotations

from backend import db
from backend.llm_client import complete_text


def build_memory_context(user_id: str, is_returning: bool) -> str:
    profile = db.get_user_profile(user_id)
    if not profile or not is_returning:
        return "This is a NEW user - you have no history on them yet."

    lines = ["This is a RETURNING user. Here is what we remember about them:"]
    if profile.get("display_name"):
        lines.append(f"- Name: {profile['display_name']}")
    if profile.get("budget_min") or profile.get("budget_max"):
        lines.append(f"- Budget range: AED {profile.get('budget_min') or '?'} - {profile.get('budget_max') or '?'}")
    if profile.get("preferred_make"):
        lines.append(f"- Preferred make: {profile['preferred_make']}")
    if profile.get("preferred_body_type"):
        lines.append(f"- Preferred body type: {profile['preferred_body_type']}")
    if profile.get("liked_listing_ids"):
        lines.append(f"- Previously liked/booked listing IDs: {profile['liked_listing_ids']}")
    if profile.get("long_term_summary"):
        lines.append(f"- Summary of past conversations: {profile['long_term_summary']}")

    if len(lines) == 1:
        lines.append("- (No specific preferences captured yet, but greet them as a returning visitor.)")

    lines.append(
        "Greet them naturally referencing at least one of these facts, without being creepy or listing them robotically."
    )
    return "\n".join(lines)


def summarize_session_and_store(user_id: str, session_id: str):
    """Called periodically (e.g. every few turns) to compress the session
    transcript into a short memory blurb, merged into the user's long-term
    profile for recall in future sessions."""
    messages = db.get_messages(session_id, limit=40)
    if len(messages) < 2:
        return

    transcript = "\n".join(f"{m['role']}: {m['content']}" for m in messages if m["content"])
    profile = db.get_user_profile(user_id) or {}
    prior_summary = profile.get("long_term_summary") or ""

    prompt = (
        "You maintain a short rolling memory of a car-shopping customer for a used-car "
        "marketplace assistant. Given the prior memory (if any) and the latest conversation "
        "transcript, produce an UPDATED memory in 1-3 concise sentences: their name (if known), "
        "what kind of car / budget / body type they're interested in, and any specific listings "
        "they liked or booked. Do not include greetings or filler. Plain text only.\n\n"
        f"PRIOR MEMORY: {prior_summary or '(none yet)'}\n\n"
        f"LATEST TRANSCRIPT:\n{transcript}\n\n"
        "UPDATED MEMORY:"
    )
    try:
        new_summary = complete_text(prompt).strip()
        if new_summary:
            db.update_user_prefs(user_id, long_term_summary=new_summary)
    except Exception:
        # Memory summarization is best-effort; never break the chat flow over it.
        pass
